[package]
name = "moss"
version = "0.1.0"
edition = "2024"

[lib]
name = "moss"
path = "src/lib.rs"

[dependencies]
combine = "4.6.6"
itertools = "0.14.0"
im = { version = "*", features = ["proptest", "serde"] }
functo_rs = "0.1.0"
literally = "0.1.3"
logos = "0.15.0"
typed-arena = "2.0.2"